version: '3.7'
services:
  database:
    image: 'postgres:15.2'
    ports:
      - '5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=health'
      - 'POSTGRES_PASSWORD=35499453'
  butt:
    build: db_docs_module
    ports:
      - '9090:9090'

